- chocolatey/Website/Views/Pages/Home.cshtml
- Now that 0.9.8.29 has been released, let's update chocolatey.org to
reflect this
- Do we have a documented release process, so that this doesn't get
overlooked in future?
> (maint) Update Latest Release Number

- chocolatey/Website/Services/MessageService.cs
- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
- This is a fixed up pull request for the work that @redsandro did in
GH-92
- A rebase was required that he wasn't comfortable doing, so this will
replace his PR
> Advise Maintainers to post to Disqus

- chocolatey/Website/Views/Packages/ListPackages.cshtml
> load feedburner icon via https

- .gitignore
- ChocolateyGallery.sln.DotSettings
- chocolatey/Website/App_Start/Configuration.cs
- chocolatey/Website/App_Start/ContainerBinding.cs
- chocolatey/Website/App_Start/IConfiguration.cs
- chocolatey/Website/App_Start/Routes.cs
- chocolatey/Website/Constants.cs
- chocolatey/Website/Controllers/PackagesController.cs
- chocolatey/Website/Services/IImageFileService.cs
- chocolatey/Website/Services/ImageFileService.cs
- chocolatey/Website/Services/PackageService.cs
- chocolatey/Website/UrlExtensions.cs
- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
- chocolatey/Website/Views/Packages/_ListPackage.cshtml
- chocolatey/Website/Views/Users/Profiles.cshtml
- chocolatey/Website/Web.config
- chocolatey/Website/Website.csproj
- chocolatey/Website/packages.config
> (GH-257) Host images locally

- chocolatey/Website/App_Start/AppActivator.cs
- chocolatey/Website/App_Start/ContainerBinding.cs
- chocolatey/Website/App_Start/SimpleInjectorInitializer.cs
- chocolatey/Website/Controllers/PackagesController.cs
- chocolatey/Website/Controllers/RssController.cs
- chocolatey/Website/DataServices/FeedServiceBase.cs
- chocolatey/Website/DataServices/V2Feed.svc.cs
- chocolatey/Website/DataServices/V2FeedPackage.cs
- chocolatey/Website/DataServices/V2SubmittedFeed.svc.cs
- chocolatey/Website/Entities/EntityRepository.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneCommon.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneFileSystem.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneIndexingJob.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs
- chocolatey/Website/Infrastructure/Lucene/PackageIndexEntity.cs
- chocolatey/Website/Infrastructure/Lucene/PerFieldAnalyzer.cs
- chocolatey/Website/Services/IIndexingService.cs
- chocolatey/Website/Services/IPackageService.cs
- chocolatey/Website/Services/PackageService.cs
- chocolatey/Website/Services/SearchFilter.cs
- chocolatey/Website/Services/SearchResults.cs
- chocolatey/Website/StringExtensions.cs
- chocolatey/Website/Web.config
- chocolatey/Website/Website.csproj
- chocolatey/Website/packages.config
- nugetgallery/Website/ExtensionMethods.cs
- nugetgallery/Website/Services/AggregateStatsService.cs
- nugetgallery/Website/Services/ISearchService.cs
This contains fixes based on looking at most recent version of the gallery on how they are using indexing and caching together.
> (GH-231) Reintroduce Lucene and make it work with Caching 

- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
> fix typo: Sofware -> Software

- chocolatey/Website/Views/Pages/About.cshtml
> (GH-360) Removed outdated information

- README.md
> Add 'getting started' instructions

- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
> Package Maintainer(s)

- chocolatey/Website/Errors/Error.html
- chocolatey/Website/Errors/ErrorLayout.cshtml
- chocolatey/Website/Views/Pages/Home.cshtml
> It's => its

- chocolatey/Website/Content/Site.css
- chocolatey/Website/Content/style.css
- chocolatey/Website/Views/Shared/Layout.cshtml
- chocolatey/Website/Views/Shared/OldLayout.cshtml
this pull request adds a Packages Search box to the main site layout and adjusts the old site layout's search box at the same time.  the search boxes now use css to expand and collapse
> epxanding / collapsing package search toolbar

- chocolatey/Website/Content/Site.css
- chocolatey/Website/Content/style.css
> (GH-554) Remove expanding search box

- chocolatey/Website/Install-LastPoshClient.ps1
- chocolatey/Website/Install.ps1
- chocolatey/Website/InstallAbsoluteLatest.ps1
- chocolatey/Website/Views/Shared/Layout.cshtml
Hi,
small maintenance issue regarding proper copyright information on the website (footer area in layout) and the PowerShell scripts.
Regards, JoKi
> (maint) update copyright year

- chocolatey/Website/Views/Blog/ChocolateyFestComingSoon.md
- chocolatey/Website/Website.csproj
Merging this branch will add the blog post "Chocolatey Fest Coming Soon" to the website.
> (blog) Chocolatey Fest Coming Soon

- chocolatey/Website/Content/Site.css
- chocolatey/Website/Content/style.css
- chocolatey/Website/Controllers/PackagesController.cs
- chocolatey/Website/Controllers/PagesController.cs
- chocolatey/Website/Controllers/UsersController.cs
- chocolatey/Website/Views/Authentication/LogOn.cshtml
- chocolatey/Website/Views/Packages/ContactAdmins.cshtml
- chocolatey/Website/Views/Packages/ContactOwners.cshtml
- chocolatey/Website/Views/Packages/ReportAbuse.cshtml
- chocolatey/Website/Views/Pages/ContactUs.cshtml
- chocolatey/Website/Views/Pages/Discount.cshtml
- chocolatey/Website/Views/Users/Register.cshtml
This PR will resolve GH-616 as it updates the website to use the invisible reCAPTCHA v2.
> (GH-616) Update reCAPTCHA

- ChocolateyGallery.sln.DotSettings
- chocolatey/Website/Controllers/PackagesController.cs
- chocolatey/Website/Controllers/PagesController.cs
- chocolatey/Website/Controllers/UsersController.cs
- chocolatey/Website/Infrastructure/Captcha.cs
- chocolatey/Website/Infrastructure/ISpamValidationModel.cs
- chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
- chocolatey/Website/RequestModels/RegisterRequest.cs
- chocolatey/Website/ViewModels/ContactOwnersViewModel.cs
- chocolatey/Website/ViewModels/ContactUsViewModel.cs
- chocolatey/Website/ViewModels/DiscountViewModel.cs
- chocolatey/Website/ViewModels/ReportAbuseViewModel.cs
- chocolatey/Website/Views/Packages/ContactAdmins.cshtml
- chocolatey/Website/Views/Packages/ContactOwners.cshtml
- chocolatey/Website/Views/Packages/ReportAbuse.cshtml
- chocolatey/Website/Views/Pages/ContactUs.cshtml
- chocolatey/Website/Views/Pages/Discount.cshtml
- chocolatey/Website/Views/Users/Register.cshtml
- chocolatey/Website/Website.csproj
- chocolatey/Website/packages.config
> (GH-628) Add server side validation of reCaptcha input

- chocolatey/Website/Controllers/ApiController.cs
Relates to #613 
(GH-613) Fix OutOfMemoryException during push
By switching from a stream to a tempfile on the filesystem
the memory footprint of the application is reduced.
By doing so a switch to `OptimizedZipPackage` is required.
This is the same implementation the NuGet Gallery is using
when it ran into similar issues.
> (GH-613) Fix OutOfMemoryException during push

- chocolatey/Website/App_Code/ViewHelpers.cshtml
- chocolatey/Website/Content/account.css
- chocolatey/Website/Content/packages.css
- chocolatey/Website/Content/scss/_base.scss
- chocolatey/Website/Content/scss/_icons.scss
- chocolatey/Website/Content/scss/_navigation.scss
- chocolatey/Website/Controllers/PackagesController.cs
- chocolatey/Website/Scripts/custom.js
- chocolatey/Website/Scripts/package-list/package-list.js
- chocolatey/Website/Views/Packages/ConfirmOwner.cshtml
- chocolatey/Website/Views/Packages/ContactAdmins.cshtml
- chocolatey/Website/Views/Packages/ContactOwners.cshtml
- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
- chocolatey/Website/Views/Packages/ListPackages.cshtml
- chocolatey/Website/Views/Packages/ManagePackageOwners.cshtml
- chocolatey/Website/Views/Packages/ReportAbuse.cshtml
- chocolatey/Website/Views/Packages/UploadPackage.cshtml
- chocolatey/Website/Views/Packages/VerifyPackage.cshtml
- chocolatey/Website/Views/Packages/_ListPackage.cshtml
- chocolatey/Website/Views/Packages/_UploadSteps.cshtml
- chocolatey/Website/Views/Pages/Home.cshtml
- chocolatey/Website/Views/Pages/Partner.cshtml
- chocolatey/Website/Views/Pages/Pricing.cshtml
- chocolatey/Website/Views/Pages/Thanks.cshtml
- chocolatey/Website/Views/Shared/_TopNavigation.cshtml
- chocolatey/Website/Views/Users/Account.cshtml
- chocolatey/Website/Views/Users/ChangePassword.cshtml
- chocolatey/Website/Views/Users/Profiles.cshtml
This PR contains some small changes that will help improve usability of the packages area. It also includes a new "User Preferences" modal that will allow users to switch between package grid view or package list view.
> Package Area Fixes and List View Option

- chocolatey/Website/Content/packages.css
- chocolatey/Website/Scripts/custom.js
- chocolatey/Website/Scripts/packages/package-details.js
- chocolatey/Website/Views/Packages/Delete.cshtml
- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
- chocolatey/Website/Views/Packages/_ListVersion.cshtml
- chocolatey/Website/Views/Users/Packages.cshtml
This PR contains style and accessibility enhancements to the DisplayPackage page:
* Minor style updates to padding/margins
* Brings consistency to package communication areas throughout the page
* Updates the Version History table to make the package communication notes easier to read and brings consistency to package status types
> Package Display Enhancements

- chocolatey/Website/Content/packages.css
- chocolatey/Website/Content/scss/_base.scss
- chocolatey/Website/Content/scss/_navigation.scss
- chocolatey/Website/Content/scss/_search.scss
- chocolatey/Website/Content/scss/chocolatey.scss
- chocolatey/Website/Controllers/DocumentationController.cs
- chocolatey/Website/Scripts/custom.js
- chocolatey/Website/Scripts/package-list/package-list.js
- chocolatey/Website/Scripts/packages/package-details.js
- chocolatey/Website/ViewModels/DocumentationViewModel.cs
- chocolatey/Website/Views/Documentation/Search.cshtml
- chocolatey/Website/Views/Documentation/_Layout.cshtml
- chocolatey/Website/Views/Packages/ListPackages.cshtml
- chocolatey/Website/Views/Shared/_SearchBox.cshtml
- chocolatey/Website/Views/Shared/_TopNavigation.cshtml
- chocolatey/Website/Website.csproj
- chocolatey/Website/gulpfile.js
In this PR:
* Adds a globals search box to the top navigation while on the home page
* Makes the search box inside the packages area more prominent
* Adds a search box in the documentation area
> Global search

- chocolatey/Website/Views/Blog/InfrastructureChangesOctober2019.md
- chocolatey/Website/Website.csproj
Add blog post to announce infrastructure changes on October 26 2019.
> (blog) Add blog post on infrastructure changes

- chocolatey/Website/Content/scss/_base.scss
- chocolatey/Website/Views/Shared/_AlertTop.cshtml
In this PR:
* Updates top alert notification to point to the new blog post explaining infrastructure changes and outages scheduled for 26 October 2019.
* Minor one time fix to style to prevent overlapping text and button on smaller screens
> Update top alert notification

- chocolatey/Website/Views/Pages/ContactUs.cshtml
Minor spelling mistake on Contact Us page fixed.
> Fixed spelling on ContactUs page

- chocolatey/Website/Views/Shared/_AlertTop.cshtml
This PR removes the top notification banner now that the maintenance window has ended.
> (maint) Remove maintenance notification banner

- chocolatey/Website/Content/packages.css
- chocolatey/Website/Content/scss/_preloader.scss
- chocolatey/Website/Scripts/custom.js
- chocolatey/Website/Scripts/packages/package-details.js
- chocolatey/Website/Views/Courses/Installation/Installing.cshtml
- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
- chocolatey/Website/Views/Packages/ListPackages.cshtml
- chocolatey/Website/Views/Pages/Install.cshtml
- chocolatey/Website/Views/Shared/MinimalLayout.cshtml
- chocolatey/Website/Views/Shared/_Loader.cshtml
- chocolatey/Website/Website.csproj
In this PR:
* Updates preloader to use pure css animations so it is not reliant on javascript to render
* Reduces javascript used in files area on the package page by using razor syntax instead
> Reduce need for JS

- chocolatey/Website/Content/scss/_icons.scss
- chocolatey/Website/Scripts/custom.js
- chocolatey/Website/Views/Pages/Pricing.cshtml
- chocolatey/Website/Views/Pages/Privacy.cshtml
- chocolatey/Website/Views/Pages/Sitemap.cshtml
- chocolatey/Website/Views/Shared/_BottomNavigation.cshtml
This PR adds in a current privacy policy as of January 1st, 2019. Minor adjustments to css and js to make collapsed navigation more precise.
> Add Privacy Policy information

- chocolatey/Website/Controllers/DocumentationController.cs
This PR addresses the issues brought up in #732 which pertains to broken documentation links.
Fixes #732
> (GH-732) Fix broken doc links

- chocolatey/Website/App_Code/ViewHelpers.cshtml
- chocolatey/Website/Services/MessageService.cs
- chocolatey/Website/Views/Packages/DisplayPackage.cshtml
- chocolatey/Website/Views/Packages/_ListPackage.cshtml
- chocolatey/Website/Views/Packages/_ListVersion.cshtml
- chocolatey/Website/Views/Users/Packages.cshtml
- chocolatey/Website/Views/Users/Profiles.cshtml
This PR contains: 
- Fixes for broken avatars in the moderation queue
- Changes to the date format to make it more universal
- Adds the package status ball to packages on a users profile page.
Fixes #740 
Fixes #647
> Redesign Phase 2 (2) Enhancements and Bug Fixes

- chocolatey/Website/_app_offline.htm
To allow people seeing the app offline person to get additional
information.
Fixes #748
> (GH-748) Add link to status page

- chocolatey/Website/App_Start/Configuration.cs
- chocolatey/Website/App_Start/ContainerBinding.cs
- chocolatey/Website/App_Start/IConfiguration.cs
- chocolatey/Website/DataServices/FeedServiceBase.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs
- chocolatey/Website/Infrastructure/Lucene/PackageIndexEntity.cs
- chocolatey/Website/Web.config
Ensure all package versions are stored in the index to reduce calls to the database.
> (GH-754) Index All Versions

- chocolatey/Website/App_Code/ViewHelpers.cshtml
- chocolatey/Website/Content/packages.css
- chocolatey/Website/Content/scss/_base.scss
- chocolatey/Website/Views/Packages/_ListVersion.cshtml
This PR contains minor styling adjustments for multiple parts of the website, but focuses on the packages area.
Adjust:
- margins on button groups
- margins on package avatars
- avatars on version table
- prevents double scrollbars on package files
> Minor Style Enhancements 

- chocolatey/Website/_app_offline.htm
This is an enhancement and updates the look and feel of the offline page. This is one page that was not touched during the initial redesign. Some content has been slightly modified to be consistent with the rest of the website.
> (GH-764) Redesign of Offline Page

- chocolatey/Website/Controllers/PackagesController.cs
Previously, when the website was using MarkdownSharp to convert markdown to cshtml, it would support the use of `###Header` instead of the correct `### Header` (notice the space). When changing over to Markdig, this was no longer supported, which meant some older packages
that were using the `###Header` syntax were not getting converted correctly.
In this PR, a few fixes were put in place to find these types of header patterns (a hash followed by no space and a character). Now, if one of these patterns are found, it will replace it with the correct syntax before Markdig takes over. This means when Markdig does its thing, it will be converted correctly onto the page resulting in the desired outcome (backwards compatibility).
Fixes #772
> (GH-772) Support backwards markdown compatibility

- Update-Database.ps1
- chocolatey/Website/App_Start/AppActivator.cs
- chocolatey/Website/App_Start/Configuration.cs
- chocolatey/Website/App_Start/ContainerBinding.cs
- chocolatey/Website/App_Start/IConfiguration.cs
- chocolatey/Website/DataServices/FeedServiceBase.cs
- chocolatey/Website/Entities/EntitiesContext.cs
- chocolatey/Website/Entities/EntityRepository.cs
- chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs
- chocolatey/Website/MethodExtensionsWrappers.cs
- chocolatey/Website/Web.config
- chocolatey/Website/Website.csproj
- nugetgallery/Website/Entities/IEntityRepository.cs
* Connect background jobs under different user
* Report on invalid search filter
* Restrict non-cached calls with search filter modifiers
* Trace execution time for Lucene and certain repositories
> (GH-793) Visibility Enhancements

- chocolatey/Website/Controllers/DocumentationController.cs
- chocolatey/Website/Views/Resources/Testimonials.cshtml
This PR address a number of broken links mentioned in #796.
> (GH-796) Address broken links on chocolatey.org

- chocolatey/Website/Controllers/CoursesController.cs
- chocolatey/Website/Controllers/PackagesController.cs
- chocolatey/Website/Controllers/UsersController.cs
- chocolatey/Website/Services/IUserService.cs
- chocolatey/Website/Services/UserService.cs
To address some security enhancements for the site.  Refer to:
- https://github.com/chocolatey/chocolatey.org/issues/810
- https://github.com/chocolatey/chocolatey.org/issues/276
- https://github.com/chocolatey/chocolatey.org/issues/811
For further details.
> Security Enhancements

- chocolatey/Website/Services/MailSender.cs
I use a basic lock to make sure we don't try to simultaneously send mail on different threads and on the same SmtpClient instance.
Since emails need to be sent synchronously (according to what I saw in the code), it makes more sense to do fix this issue this way instead of using the ThreadPool (eg http://stackoverflow.com/a/16438292/18475) or Task (like I suggested).
Otherwise, an other solution would be to instantiate SmtpClient each time we need it instead of using the current singleton.
> (GH-379) Add sync lock on send mail to avoid async issues

- chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs
Lucene docs recommend handling OutOfMemoryException by disposing the IndexWriter. See here: https://lucenenetdocs.azurewebsites.net/api/Lucene.Net/Lucene.Net.Index.IndexWriter.html
This should prevent index corruption and allow us to simply re-create the index writer and retry the commit. If the second commit attempt fails, then the error will be raised. This should hopefully give us some breathing room in high load situations.
Related: #829 
/cc @ferventcoder @gep13
> (GH-829) Add dispose-and-retry to index commits

- chocolatey/Website/Content/scss/_navigation.scss
- chocolatey/Website/Scripts/custom.js
This PR addresses:
* Navigation dropdown spacing issues when the top alert banner is dismissed.
* Adjust spacing of navigation items to prevent overlapping of items on smaller screens
> Top navigation style adjustments

- chocolatey/Website/Controllers/PagesController.cs
- chocolatey/Website/ViewModels/ContactQuickDeploymentViewModel.cs
- chocolatey/Website/Views/Pages/ContactQuickDeployment.cshtml
Adds an additional field to the QDE form to allow users to select the hypervisor they are using.
> Add hypervisor field to QDE form

- chocolatey/Website/Views/Pages/Pricing.cshtml
Change 'Build-in PowerShell Functions' to 'Built-in Powershell Functions'
> Fix typo on pricing page

- chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs
Currently we're hitting some issues where accessing the index writer can cause errors indicating it has been closed, or just straight up NullReferenceExceptions.
It's likely these occur as a result of accessing the `_indexWriter` from multiple threads, and because we're not properly removing it from the WriterCache dictionary. This PR should ensure that requests for the index writer block during the recovery sequence, so that it has time to be recreated properly, and the reference to the broken writer in the cache is removed correctly.
+ Created new Index property and updated all _indexWriter references.
+ Lock in the getter for Index so requests block during recovery.
+ Removed some redundant code in `EnsureIndexWriter` that was evading the only lock we had already in place.
+ Ensure we …
> (#853) Lock index writer when recovering from errors.

- chocolatey/Website/Content/pages.css
- chocolatey/Website/Content/scss/_base.scss
- chocolatey/Website/Content/scss/_callouts.scss
- chocolatey/Website/Content/scss/_lists.scss
- chocolatey/Website/Controllers/BlogController.cs
- chocolatey/Website/Views/Blog/EnableRemoteWorkQuickDeploymentEnvironment.md
- chocolatey/Website/Views/Blog/HowToDeliverWorkFromHomeInUnprecedentedTimesWithChocolateySelfServiceAnywhere.md
- chocolatey/Website/Views/Pages/MarkdownPostArticle.cshtml
- chocolatey/Website/Website.csproj
PR Contains:
* New blog "How to Deliver Work From Home in Unprecedented Times with Chocolatey Self-Service Anywhere"
* Updates to Markdig to support emojis and custom containers
* Blog style enhancements
* Adds LinkedIn share button to blog
> (blog) Work From Home/Chocolatey Self-Service Anywhere Blog and Style Updates

- chocolatey/Website/Content/scss/_countdown.scss
- chocolatey/Website/Views/Pages/Home.cshtml
Updates the blue announcement section on the home page from Covid-19
updates to information about the upcoming webinar "Enable Your Remote
Workforce by Implementing Modern Infrastructure with Chocolatey".
> (layout) Add Webinar Announcement to Home Page

- chocolatey/Website/App_Start/Routes.cs
- chocolatey/Website/Content/scss/_base.scss
- chocolatey/Website/Views/Pages/Home.cshtml
Updates the announcements on the home page to unite the sections on deployments and updates the webinar to the new Deployments Webinar.
> (layout) Adjust Home Page Announcements

- chocolatey/Website/Views/Shared/MinimalLayout.cshtml
- chocolatey/Website/Views/Shared/_TopNavigation.cshtml
Adds scripts to the body on every page.
> (maint) Add Scripts to Body

- chocolatey/Website/Views/Products/ChocolateyForBusiness.cshtml
Updates the pricing cards on the bottom of the C4B page to reflect
updates made in commit:
https://github.com/chocolatey/chocolatey.org/commit/74beaa64689245d39d1ce9f6f95cabe95e0c8bcd
> (maint) Reflect Pricing Updates on C4B Page

- chocolatey/Website/Views/Products/ChocolateyForBusiness.cshtml
- chocolatey/Website/Views/Shared/_TopNavigation.cshtml
In this PR:
- Adds a link to the C4B page to the Solutions dropdown in the top navigation
- Adds content about CCM Deployments to the C4B page
> Add Content on C4B and Deployments

- chocolatey/Website/Content/account.css
- chocolatey/Website/Infrastructure/Captcha.cs
- chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
- chocolatey/Website/Views/Authentication/LogOn.cshtml
- chocolatey/Website/Views/Packages/ContactAdmins.cshtml
- chocolatey/Website/Views/Packages/ContactOwners.cshtml
- chocolatey/Website/Views/Packages/ReportAbuse.cshtml
- chocolatey/Website/Views/Pages/ContactBlocked.cshtml
- chocolatey/Website/Views/Pages/ContactDiscount.cshtml
- chocolatey/Website/Views/Pages/ContactGeneral.cshtml
- chocolatey/Website/Views/Pages/ContactPartner.cshtml
- chocolatey/Website/Views/Pages/ContactQuickDeployment.cshtml
- chocolatey/Website/Views/Pages/ContactSales.cshtml
- chocolatey/Website/Views/Pages/ContactSalesOther.cshtml
- chocolatey/Website/Views/Pages/ContactTrial.cshtml
- chocolatey/Website/Views/Pages/Discount.cshtml
- chocolatey/Website/Views/Users/Register.cshtml
In an effort to reduce the amount of spam, reCAPTCHA has been updated
from v2 to v3. If reCAPTCHA returns a score of less than 0.5, it is
determined that this is likely a bot, and the form will not be allowed
to submit and an error message will appear on the form.
Docs:
https://developers.google.com/recaptcha/docs/v3
> (GH-937) Update to reCAPTCHA v3

- chocolatey/Website/Scripts/chat/chat.js
- chocolatey/Website/Views/Documentation/DocumentationLayout.cshtml
- chocolatey/Website/Views/Events/ChocolateyDeployments.cshtml
- chocolatey/Website/Views/Events/EnableYourRemoteWorkforceByImplementingModernInfrastructureWithChocolatey.cshtml
- chocolatey/Website/Views/Events/Home.cshtml
- chocolatey/Website/Views/Pages/Compare.cshtml
- chocolatey/Website/Views/Pages/ContactDiscount.cshtml
- chocolatey/Website/Views/Pages/ContactPartner.cshtml
- chocolatey/Website/Views/Pages/ContactQuickDeployment.cshtml
- chocolatey/Website/Views/Pages/ContactSales.cshtml
- chocolatey/Website/Views/Pages/ContactSalesOther.cshtml
- chocolatey/Website/Views/Pages/ContactTrial.cshtml
- chocolatey/Website/Views/Pages/ContactUs.cshtml
- chocolatey/Website/Views/Pages/Partner.cshtml
- chocolatey/Website/Views/Pages/Pricing.cshtml
- chocolatey/Website/Views/Pages/UseCases.cshtml
- chocolatey/Website/Views/Products/ChocolateyForBusiness.cshtml
- chocolatey/Website/Views/Products/Home.cshtml
- chocolatey/Website/Views/Resources/CaseStudies.cshtml
- chocolatey/Website/Views/Resources/Features.cshtml
- chocolatey/Website/Views/Resources/Home.cshtml
- chocolatey/Website/Views/Resources/Post.cshtml
- chocolatey/Website/Views/Resources/SuccessStories.cshtml
- chocolatey/Website/Views/Resources/Testimonials.cshtml
- chocolatey/Website/Views/Resources/Videos.cshtml
- chocolatey/Website/Views/Resources/_Layout.cshtml
- chocolatey/Website/Views/Shared/ChatLayout.cshtml
- chocolatey/Website/Views/Solutions/SelfServiceAnywhere.cshtml
- chocolatey/Website/Web.config
- chocolatey/Website/Website.csproj
Implements a chat feature that users can ask/interact with Chocolatey
members about Chocolatey for Business. This is restricted to certain
pages that users might navigate to to find out more about the Business
features Chocolatey offers.
> (GH-972) Implement Chat Feature

- chocolatey/Website/Views/Events/ChocolateyDeploymentSchedules.cshtml
- chocolatey/Website/Views/Events/Files/01-05-ChocolateyDeploymentSchedules.md
- chocolatey/Website/Views/Pages/Home.cshtml
- chocolatey/Website/Views/Pages/_CollapsingRightSidebarContent.cshtml
Updates the time of the upcoming webinar from 9:00 CST to 10:00 CST.
> (events) Update CCM Webinar Time

- chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml
- chocolatey/Website/Views/Events/Files/01-06-12DaysOfChocolatey.md
Adds in the registration link to the 12 Days of Christmas event.
> (events) Add Register Link for 12 Days Event

- chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml
- chocolatey/Website/Views/Events/Files/01-06-12DaysOfChocolatey.md
Adds George James as a speaker for the Ansible webinar that takes place
during the 12 Days of Chocolatey.
> (events) Add Speaker to 12 Days of Chocolatey

- chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml
- chocolatey/Website/Views/Events/ChocolateyAndAnsible.cshtml
Updates a css class that is needed to configure the countdown timer on
an events page. This also adds the new countdown markup to the Ansible
Webinar page so that the timer works correctly.
> (events) Update CSS for Countdown Timer

- chocolatey/Website/Scripts/custom.js
- chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml
This adds functionality to make webinar links available for on demand
replay for multi events. Also the YouTube playlist has been added to the
12 Days page so users can watch if they missed a day.
> (events) Make Certain Multi Events On Demand
