chocolatey/chocolatey.org

chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Web.config
- In order to allow configuration of Disqus Shortname, i.e. change it
for multiple deployment environments, moved it into the web.config file.
- We should then be able to update the web.config file settings based on
whether we are running locally, i.e. the default, or on AppHarbor, or on
chocolatey.org
=> Made Disqus Shortname Configurable

chocolatey/Website/App_Start/Routes.cs, chocolatey/Website/Controllers/PackagesController.cs, chocolatey/Website/RouteNames.cs, chocolatey/Website/Services/IMessageService.cs, chocolatey/Website/Services/MessageService.cs, chocolatey/Website/ViewModels/CommentViewModel.cs, chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Website.csproj
Attempts to implement requirements for #27
- Added new MessageService method to construct email to current maintainers
- Added same method signature to interface
- Created new ViewModel for sending id and text of comment from the client
- Added new PackagesController method for accepting post from client when new Disqus comment is added
- Added new Route to handle mapping to new controller method
=> Adding Disqus Notification Emails

chocolatey/Website/Services/MessageService.cs, chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Web.config
- Changed default value of ForceSSL to be false (so that it will work
locally)
- Updated notes above Disqus thread to indicate new notifications
- Following discussion with Rob, built up comment Post Url in a way that
it will hopefully work locally, and on staging and production
=> Changed Comment Post Url

chocolatey/Website/Controllers/JsonApiController.cs, chocolatey/Website/Services/IMessageService.cs, chocolatey/Website/Services/MessageService.cs, chocolatey/Website/Views/Packages/ManagePackageOwners.cshtml, chocolatey/Website/Website.csproj
Allow maintainer the ability to add a maintainer without need for
confirmation. This will assist when adding the chocolatey user as a
maintainer. That way there is only a confirmation email instead of an
email that requires action.
This also allows a moderator to remove themselves from being a package
maintainer.
=> (GH-151) Moderator can add maintainer directly

chocolatey/Website/App_Start/Routes.cs, chocolatey/Website/DataServices/V2SubmittedFeed.svc, chocolatey/Website/DataServices/V2SubmittedFeed.svc.cs, chocolatey/Website/RouteNames.cs, chocolatey/Website/Website.csproj
Provide ability to query, via oData, only from the packages which are
currently in a submitted state.
Without this change, automated package moderation will not be able to
get started.
Closed #175
=> oData Feed for Submitted Packages

chocolatey/Website/Views/Documentation/HowToHostFeed.cshtml
Remove mentioning of ProGet being able to be installed using Chocolatey, since that package is broken, Inedo admitted that they haven't touched it since ages and show no interested in fixing it (instead people should build their own scripts)
=> Remove mentioning of ProGet Chocolatey package

chocolatey/Website/Controllers/UsersController.cs
Display a package as listed if it has at least one listed version, as suggested in #173.
I also changed how version is determined: instead of getting the max version (on a string...), I order by version (using SemanticVersion) descending. This means that max version is displayed but its related published date as well for instance.
=> (GH-104) Fix listed packages

UpdateDocumentation.ps1
Workaround for a discrepancy between GitHub and Pandoc output.
Pandoc keeps dots in ids while GitHub doesn't:
https://github.com/chocolatey/choco/wiki/Installation#install-with-cmdexe (leads right to the section)
https://chocolatey.org/install#install-with-cmdexe (leads nowhere)
=> Remove dots from header ids

chocolatey/Website/ViewModels/ListPackageItemViewModel.cs, chocolatey/Website/Website.csproj
this PR fixes the issue mentioned on gitter that moderators can't see unlisted packages unless they also are the owners of that package.
The fix could instead be changed at the following location: https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Views/Packages/_ListVersion.cshtml#L9
if that is preferred.
/CC @ferventcoder 
fixes #493
=> (GH-493) View unlisted packages as a moderator

chocolatey/Website/Controllers/ApiController.cs
With this change only packages with at least one approved
stable release is allowed to push multiple new versions.
PreReleases are also considered when checking if a version
is in the submitted state (Ignored if they are approved/Exempted though).
fixes #486
=> (GH-486) Added check if existing packages is in submitted state

chocolatey/Website/Install.ps1
Do not output the creation of the temporary `chocInstall` directory:
```plain
==> default: Running C:\vagrant\provision-chocolatey.ps1...
==> default: Downloading specific version of Chocolatey: 0.10.7
==> default: Mode                LastWriteTime         Length Name                                                                  
==> default: ----                -------------         ------ ----                                                                  
==> default: d-----         8/7/2017   6:42 AM                chocInstall                                                           
==> default: Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.7.
```
=> do not output the created temporary directory

chocolatey/Website/Views/Documentation/About.cshtml
Ansible was missing from the list of devops tools.
=> Add Ansible to the text of the homepage.

chocolatey/Website/Views/Documentation/HowToSetUpChocolateyServer.cshtml, chocolatey/Website/Views/Documentation/HowToSetupOfflineInstallation.cshtml
Updated the CM table at https://chocolatey.org/docs/how-to-setup-offline-installation#chocolatey-integration-implementation-with-configuration-managers to reflect recent changes in Ansible that will be part of the Ansible 2.7 release. Also add a few more bits and pieces around an Ansible Galaxy role that can be used to setup Chocolatey Server.
=> Updated docs for recent changes in Ansible that relate to Chocolatey

chocolatey/Website/Controllers/PackagesController.cs, chocolatey/Website/PackagesController.generated.cs, chocolatey/Website/ViewModels/ContactAdminsViewModel.cs, chocolatey/Website/Views/Packages/ContactAdmins.cshtml, chocolatey/Website/Website.csproj
The Report Abuse form and the Contact Admins form previously shared the
ReportAbuse view model. With the addition of the required check box to
the ReportAbuse view model in a previous commit, this made the Contact
Admins form unable to submit. The Contact Admins form was expecting a
required check box element, when there was none.
A new view model has been created specifically for the Contact Admins
form, and all appropriate files have been updated to reflect the change.
=> (GH-645) Add ContactAdmins view model

chocolatey/Website/Controllers/PackagesController.cs, chocolatey/Website/Services/IPackageService.cs, chocolatey/Website/Services/PackageService.cs, chocolatey/Website/Views/Packages/DisplayPackage.cshtml
Merging this allows the moderators to restart the validation tests.
See screenshot:
Merging this fixes #648
=> (GH-648) Allow moderator to restart validator

chocolatey/Website/Web.config
A snippet has been added to Web.config to allow IIS to send the X-Frame-Options header. This X-Frame-Options header is used to avoid clickjacking attacks by ensuring that content on Chocolatey.org can not be embedded into other sites.
More information about this response header can be found at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
=> (GH-684) Add X-Frame-Options header for IIS

chocolatey/Website/Views/Pages/Home.cshtml, chocolatey/Website/Views/Pages/Products.cshtml, chocolatey/Website/Views/Pages/WhyChocolatey.cshtml, chocolatey/Website/Views/Styleguide/Sections.cshtml
Thanks for the new Chocolatey website. I really like the new UI.
One improvement I want to send you with this PR is that the packer `docker` is deprecated. That was originally the Docker CLI where nothing else existed yet on Windows. The most relevant package using Docker on a recent Windows 10 machine is the package `docker-desktop`. 
See also #609
=> Use docker-desktop package in animation

chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs, chocolatey/Website/Infrastructure/Lucene/PackageIndexEntity.cs, chocolatey/Website/Views/Documentation/Installation.cshtml
Id and Title need to be boosted quite a bit more in relevance for
search results. Add them to the package index entity with a higher
boost on id and title.
- Increase Id-Exact field to 4.5f from 2.5f in the index
- Add an Title-Exact field and give it a 4.0f boost in the index
- In the AND query (conjunction), boost it from 2.0f to 4.0f
- Boost exact Id query from 2.5f to 7.0f
- Add exact title query to search against Title-Exact with a 5.0f boost
- Add wildcard Title query to search against title.
- Remove the download count boosting on search results by relevance
Closes #699
=> (GH-699) Fix relevance in search results

chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Views/Pages/Install.cshtml, chocolatey/Website/Views/Pages/Pricing.cshtml
In this PR:
* Adds functionality that will automatically expand a collapsed element if the hash is found within the URL, and will also scroll to that element on load
* Adds hash to URL when any collapsed element is clicked on, allowing easy copy/paste
* Functions similarly to how tab navigation currently is implemented.
=> (layout) Make collapsed elements navigatable by url

chocolatey/Website/Content/scss/_search.scss, chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Pages/Home.cshtml
The javascript controlling the typewriter animation was not supported
on Internet Explorer. As a result, the typewriter animation and any JS
after that inside the same file was not working properly and
producing errors. The snippet has been rewritten to work on all
browsers, and a result lazy loading images and the global search now
works on IE.
A few styles were updated on the home page and search box to help with
IE display.
=> Make typewriter JS compatible with IE

UpdateDocumentation.ps1
When you run `UpdateDocumentation.ps1` for the first time, with an empty choco.wiki folder, the submodule does not update and the script fails to run. The first time you need to initialize the submodule and then update it.
=> (maint) init choco.wiki submodule if folder empty

chocolatey/Website/Controllers/PackagesController.cs, chocolatey/Website/Views/Packages/DisplayPackage.cshtml
This allows us to restart the package-cacher
for an existing package, giving us the possibility
to trigger a new download of the cached version of
installers.
Merging this closes #675
=> (GH-675) Restart package cacher for a package

chocolatey/Website/Content/scss/_base.scss, chocolatey/Website/Views/Packages/DisplayPackage.cshtml
With the new redesign, some permissions of maintainers and
moderaters were lost. After comparing the DisplayPackage.cshmtl now to
how it was before the redesign, a few changes have been made to the
layout to ensure these permissions were reinstated. The overall
look/feel remains the same.
Fixes #728
=> (GH-728) Reinstate lost moderation permissions

chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Web.config
With the refactoring of the Files section to use razor syntax instead
of javascript, one piece of content was wrapped inside of a
`(!string.IsNullOrWhiteSpace(file.FileContent))` that was not supposed
to be. This was causing files with no content to not be displayed. The
Files section has been adjusted slightly so that files with no content
will still be displayed.
Now:
After enabling multiple file types to show a checksum, such as the .msixbundle file:
Fixes #736
Fixes #682
=> (GH-736, GH-682) Show files with no content and add checksums

chocolatey/Website/App_Start/AppActivator.cs, chocolatey/Website/Web.config
These background jobs are prone to stopping without any warning, with
the only way to start them again properly being to restart the website.
This is far from ideal, and as such, the decision has been taken to
remove them from the site, and instead run them elsewhere.
Fixes #750
=> (GH-750) Remove jobs for updating database 

chocolatey/Website/Controllers/DocumentationController.cs
Some of the internal links inside the documentation files do not contain hyphens in between words when they are supposed to. The links still work how they are, but they are pointing to a different url than what has already been established.
A new method has been added to handle adding these hyphens in between words much similarly as file names are being handled. This ensures all urls are consistent throughout the documentation area.
For example, if the link below was referenced within a documentation file (as like on the home page, second link), it would be rendered as https://chocolatey.org/docs/gettingstarted#what-is-chocolatey and no left side navigation is highlighted.
Now with the fix (correct link) https://chocolatey.org/docs/getting-started#what-is-chocolatey and the left side …
=> (GH-756) Make internal doc links contain hyphens

chocolatey/Website/Scripts/packages/package-details.js
Inside of any text editor that takes advantage of the EasyMDE library, an eye with the word "Preview" is shown. In cases where there are more than one of these text editors on a page, the word "Preview" is being appended twice.
The code for appending the word "Preview" has been slightly modified to address this problem. Since the code for this is inside an `each()` loop, the identifier needs to originate from `$(this)`, or else the error above will occur.
Fixes #752
=> (GH-752) Prevent double "Preview" in text editor toolbar

chocolatey/Website/App_Start/ContainerBinding.cs, chocolatey/Website/DataServices/FeedServiceBase.cs, chocolatey/Website/DataServices/V2Feed.svc.cs, chocolatey/Website/DataServices/V2SubmittedFeed.svc.cs, chocolatey/Website/Entities/EntitiesContext.cs, chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs, chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs, chocolatey/Website/Infrastructure/Lucene/PackageIndexEntity.cs, chocolatey/Website/Services/PackageService.cs, chocolatey/Website/Services/SearchFilter.cs
There were a number of issues identified in the move to store all results in the index (#754). Most of these are addressed by this request:
* Set timeout for connection itself to allow for more than 110  seconds to finish querying out all records
* Update Lucene Index Job with better timings and timeouts
* Adjust package index fields.
* Don't force a full rebuild every package addition/update
* Store all unlisted as those should also be returned in some instances
* Move FindPackagesById to use the index when storing all results
* Fix the search filters a bit with the id, tags, author precursors
* Ensure index is updated properly when a package is updated and storing all results
Fixes #761
Fixes #762
=> (GH-762)(GH-761) Lucene Index Fixes and Enhancements

chocolatey/Website/Controllers/PackagesController.cs, chocolatey/Website/ViewModels/PackageListViewModel.cs, chocolatey/Website/Views/Packages/ListPackages.cshtml
This PR addresses 3 main issues that relate to package status filtering and incorrect number counts while in the moderation queue. 
Fixes #743 
Fixes #731 
Fixes #741
=> Moderation Filtering and Search Result Fixes

chocolatey/Website/Controllers/PackagesController.cs
Currently, if a user is to go to https://chocolatey.org/packages?q=&moderatorQueue=true they will be hit with a 404 page.
This is due to the moderationStatus filter being null. Now, if the filter is null then it will be defaulted to "AllModerationStatuses" which will show all the packages in moderation as expected. With this in place, the link above now works as intended.
Fixes #783
=> (GH-783) Fix broken link to moderator queue

chocolatey/Website/Views/Pages/Pricing.cshtml
Changed name of route from features-shims to feature-shim as used in
other place throughout the site.
Fixes #788
=> (GH-788) Fix link to shim feature page 

chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Views/Packages/VerifyPackage.cshtml, chocolatey/Website/Website.csproj, chocolatey/Website/packages.config
In the package description area, currently 4 spaces is being interpreted as a code block when that is the unintended outcome. The changes here will disable this feature. This is implemented on both the Verify Package page and the Display Package page.
Reference on a similar issue: https://github.com/lunet-io/markdig/issues/348 
Package in pictures: https://chocolatey.org/packages/powershell-preview#description
Before:
After:
=> (GH-790) Prevent 4 spaces from converting to code blocks

chocolatey/Website/Views/Blog/RemoveSupportForOldTLSProtocols.md, chocolatey/Website/Website.csproj
Blog post to announce the deprecation of older TLS protocols (< 1.2).
=> (GH-778) Blog announcement to remove old TLS

chocolatey/Website/Views/Packages/ContactOwners.cshtml, chocolatey/Website/Views/Packages/DisplayPackage.cshtml
This PR contains:
* Enhancements to the SEO on any package page. Now when sharing the package through a link, the package description will appear instead of a generalized description about Chocolatey.
* Fixes issues of seeing a blank screen when trying to contact an owner of package that has opted out of email
* Fixes virus scan results highlighting over 10
Fixes #801 
Fixes #819
=> Package area bug fixes and seo enchancements

chocolatey/Website/Content/scss/_navigation.scss, chocolatey/Website/Controllers/AuthenticationController.cs, chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Shared/_AuthenticationSubNavigation.cshtml
The changes here update the logoff action to a `HttpPost` instead of an
`HttpGet` which allows the usage of an antiforgery token to prevent any
CSRF attacks on logout.
=>  (GH-818) Prevent CSRF attack on Logout

chocolatey/Website/Scripts/install-steps/install-steps.js, chocolatey/Website/Scripts/packages/package-details.js, chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Views/Packages/VerifyPackage.cshtml, chocolatey/Website/Views/Pages/Install.cshtml, chocolatey/Website/Website.csproj
Currently when going to the Install or Verify Package (step 2 when uploading a package) page, there is a JS error of `'querySelectorAll' of undefined`, which is being caused by a snippet of JS that is meant to be run specifically on the Package Display page.
This error is causing the install steps area not to work on the Install page, and the file that contains this code is actually not needed at all on the Verify Package page.
The JS snippet that controls the install steps has been moved to its own JS file, which allows the `package-details.js` to be removed entirely from the 2 pages that do not need it. This cuts down on the amount of unnecessary JS on these 2 pages. The `install-steps.js` file has been added to the Package Display page and the Install page as those are the 2 pages that …
=> (GH-827) Fix JS on Install and Verify Package page

chocolatey/Website/Views/Authentication/LogOn.cshtml, chocolatey/Website/Views/Packages/ContactAdmins.cshtml, chocolatey/Website/Views/Packages/ContactOwners.cshtml, chocolatey/Website/Views/Packages/ReportAbuse.cshtml, chocolatey/Website/Views/Pages/ContactBlocked.cshtml, chocolatey/Website/Views/Pages/ContactDiscount.cshtml, chocolatey/Website/Views/Pages/ContactGeneral.cshtml, chocolatey/Website/Views/Pages/ContactPartner.cshtml, chocolatey/Website/Views/Pages/ContactSales.cshtml, chocolatey/Website/Views/Pages/ContactSalesOther.cshtml, chocolatey/Website/Views/Pages/ContactTrial.cshtml, chocolatey/Website/Views/Pages/Discount.cshtml, chocolatey/Website/Views/Users/Register.cshtml
Currently, the Contact Admins, Contact Owners, and Report Abuse forms do not submit, and instead trigger the LogOut action. This is due to the recaptcha JavaScript that is on these pages. JavaScript was previously being used on forms that needed recaptcha to add an ID element to the form, however this method does not work when there is more than one form on the page. The LogOff form for was mistakingly getting the recaptcha ID, which in tern was triggering another function to make the LogOff form submit (and logoff the user) whenever the intended form with recaptcha was submitted.
Instead of using JavaScript to identify forms that need the recaptcha ID, the ID has been added using razor syntax to the specified forms that need it. While only 3 forms need this at this time, the syntax has …
=> (GH-830) Allow package related forms to submit

chocolatey/Website/Controllers/PagesController.cs, chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Packages/DisplayPackage.cshtml, chocolatey/Website/Views/Packages/ListPackages.cshtml, chocolatey/Website/Views/Shared/_AuthenticationSubNavigation.cshtml
The first page of the package area `/packages` is heavily cached. For this reason, we need to get the username via ajax call in order for the `profiles` link in the sub navigation to work. Now that we have the username, JavaScript can inject it on load, so that the link will work even if the page is heavily cached.
Method of retrieving the username in `PagesController.cs` is similar to how it is implemented in `UsersController.cs`.
This PR also prevents the flashing of the `noscript` text on load in the authentication sub navigation.
Fixes #835
Fixes #838
=> (GH-835, GH-838) Get username on authentication via ajax and prevent noscript flicker

chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Pages/_SelfServiceResources.cshtml, chocolatey/Website/Views/Resources/Files/04-02-C4BSelfServiceAndChocolateyGuiIntro.md, chocolatey/Website/Views/Shared/_AlertTop.cshtml
Currently, the top alert banner will be removed once a user clicks on
it by using a session storage item. Now, the top alert banner will stay
in place unless the user specifically clicks on the "X" in the right
corner to remove it.
Minor updates to the JS snippet controlling this feature was made. The
changes also eliminates the flash of red sometimes seen on page load if
a user has removed the alert.
Also includes:
* Typo fix
* Adds suggested video from Part 1 video
=> Remove Top Alert Only on "X" Click and Maintenance

chocolatey/Website/Content/scss/_base.scss, chocolatey/Website/Content/scss/_lists.scss
Due to recent changes, the CSS that controls custom list styling has
been been moved to it's own scss file. The small snippet from
`_base.css` was missed during this transition and is now causing a
styling error on the profile page.
The snippet has been moved to the appropriate file which makes the
profile page appear how it should.
=> (layout) Adjust CSS on Profile Page

chocolatey/Website/Views/Pages/Covid19.cshtml
Chocolatey has created a team on Folding@home. This adds the
information to the Covid-19 home page to allow other users to learn
more and download the Folding@home Chocolatey package.
=> Add Folding@home Information to Covid-19 Home Page

chocolatey/Website/Controllers/DocumentationController.cs
With the addition of this extension, and emojis that might be used in
the documentation area in markdown will be converted to the appropriate
icon.
More info about this added extension at:
https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/EmojiSpecs.md
=> (docs) Add Markdig Emoji Extension to Docs

chocolatey/Website/Content/scss/_callouts.scss, chocolatey/Website/Scripts/custom.js
Adds styling for blockquote elements to resemble the usage of "callouts"
throughout the website. This will mostly be used when converting files
from markdown, otherwise the standard "callout" syntax should be used.
=> (layout) Add Styling for Blockquotes

chocolatey/Website/ViewModels/ContactQuickDeploymentViewModel.cs
Updates the spelling of "VMWare" to "VMware" as expected.
=> (maint) Fix typo on QDE form

chocolatey/Website/Views/Pages/Sitemap.cshtml, chocolatey/Website/Views/Pages/WhyChocolatey.cshtml, chocolatey/Website/Views/Shared/_BottomNavigation.cshtml, chocolatey/Website/Views/Shared/_TopNavigation.cshtml
A recent change updated the routes to the Products page to include
another sub page products/chocolatey-for-business where in the URL
`productName` points the the page that should be displayed.
In order to show the main url of /products, `productName` should be
equal to "home" because that is the top level page. The url's to the
main /products page have been updated throughout the website.
=> (maint) Update Links to Product Pages

chocolatey/Website/Views/Pages/Sitemap.cshtml, chocolatey/Website/Views/Resources/Home.cshtml, chocolatey/Website/Views/Shared/_BottomNavigation.cshtml, chocolatey/Website/Views/Shared/_TopNavigation.cshtml
Adds the COVID-19 Resources to the main resource area page. In
addition, a link to the COVID-19 Page has been added under "Learn" in
the top nav, footer, and sitemap.
=> (layout) Link to COVID-19 Resources

chocolatey/Website/App_Start/AppActivator.cs
Some CDNs and iconUrl servers have disabled TLS versions below 1.2, causing problems for the WebClient in .NET 4.0 (see reports about the Statically CDN failing for icons).
Targeting a newer version of .NET should should remove the need for this, but for now this should fix #652 .
I've tested this change on Windows 10 with the Statically CDN to confirm that it resolved the problem.
=> Enable TLS 1.2 & 1.3 Icon Downloading

chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Events/Files/01-00-ExampleEvent.md, chocolatey/Website/Views/Events/Files/01-01-EnableYourRemoteWorkforceByImplementingModernInfrastructureWithChocolatey.md, chocolatey/Website/Views/Events/Files/01-02-ChocolateyDeployments.md, chocolatey/Website/Views/Events/Home.cshtml, chocolatey/Website/Views/Events/README.md
The countdown timers on the event pages were off due to not being
converted to the correct timezone. Now, the `EventDate` is set to UTC
across the board to ensure consistency. This field is only used to set
the countdown clocks on the individual event, and to move items on the
main event page from "upcoming" to the "on-demand" sections.
=> (maint) Update Timers on Event Pages

chocolatey/Website/Controllers/ApiController.cs
There should be no more than a certain number of versions of a package in moderation at one time. If there are, it means that under normal circumstances communications are not working appropriately.
Closes #865
=> (GH-865) Limit number of package versions allowed in a submitted status

chocolatey/Website/Views/Packages/UploadPackage.cshtml
There was is a small typo on the deprecated upload package page, this PR corrects that typo.
=> (maint) Correct typo on upload package page

chocolatey/Website/Views/Pages/Home.cshtml
Note: This is to be merged after the Deployments Webinar has ended.
Updates the webinar announcement on the home page to "Watch On-Demand"
instead of "Reserve My Spot", as the webinar is now over and the replay
is available.
=> (layout) Update Home Page Announcement

chocolatey/Website/Controllers/PackagesController.cs, chocolatey/Website/Services/IPackageService.cs, chocolatey/Website/Services/PackageService.cs, chocolatey/Website/Views/Packages/DisplayPackage.cshtml
Added the ability to exempt a package from the package-validator. This
only happens for the current package version.  The intention is that
validation is by based for a specific version to allow moderation to
continue, and appropriate work will be done on the next package version
to fix the issues that the validator brought up.
This adds the following checkbox:
Fixes #902
=> (GH-902) Add ability to exempt validation

chocolatey/Website/Views/Packages/DisplayPackage.cshtml
There is some ambiguity, both in the code, and in the resulting legend,
about the bounds of the light, medium and dark virus scan levels.  The
code has been updated to make it clear what those ranges are, and they
now match up to what is displayed in the legend.
Fixes #905
=> (GH-905) Clarify what virus scan results mean

chocolatey/Website/Views/Courses/CreatingChocolateyPackages/BuildingTestingAndPushing.cshtml, chocolatey/Website/Views/Documentation/Files/CreatePackages.md
Remove documentation references to manually uploading package to website, as this functionality has been disabled.
=> Delete old instructions from package upload docs

chocolatey/Website/Scripts/packages/package-details.js, chocolatey/Website/Views/Packages/DisplayPackage.cshtml
There is a slight bug in the Easymde JS library used that when a text
editor is hidden on load inside a collapsed or tabbed item, the content
is not displayed until the editor is clicked on. A fix has been
put in place that will basically "refresh" the editor whenever the
hidden editor becomes visible. A new class must be applied to the
collapsible item of "text-editor-refresh" in order for this JS to
trigger.
More information on this bug and fix here:
https://github.com/Ionaru/easy-markdown-editor/issues/208#issuecomment-645656131
=> (GH-922) Show Content Inside Collapsed Text Editor

chocolatey/Website/Content/scss/_base.scss, chocolatey/Website/Content/scss/_collapsing-sidebar.scss, chocolatey/Website/Content/scss/chocolatey.scss, chocolatey/Website/Content/scss/purge.scss, chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Packages/ListPackages.cshtml, chocolatey/Website/Views/Pages/_CollapsingRightSidebar.cshtml, chocolatey/Website/Views/Pages/_CollapsingRightSidebarContent.cshtml, chocolatey/Website/Views/Shared/_TopNavigation.cshtml, chocolatey/Website/Website.csproj
An announcement bar has been added that will appear on the right hand
side of the screen while on desktop, and full screen while on mobile.
The announcement bar is slightly different on the package listing page
then on the rest of the website, as it is static and always visible. On
the rest of the website, there is a new button that is located on the
right hand side of the screen that will show/hide this announcement
area when clicked. While on mobile, this switches to a button that is
added to the top navigation bar.
The announcements are set to "shuffle" on reload, so that a user will
potentially see different announcements while navigating throughout the
website.
=> (layout) Add Right Side Announcement Bar

chocolatey/Website/Content/scss/purge.scss
While on mobile, the Gitter chat box is very tiny and unreadable. This
slight change in CSS adjust the chat box to take up the entire screen
on a mobile device so that it is easier to type and read.
=> (layout) Adjust Gitter Chat Box for Mobile

chocolatey/Website/Services/CryptographyService.cs, chocolatey/Website/Services/PackageService.cs, nugetgallery/Website/Services/ICryptographyService.cs
Rather than computing it from a byte[]. Using the ReadAllBytes method
is causing an OutOfMemory exception to occur with larger packages. The
ComputeHash method that is being used can also accept a Stream, rather
then a byte[], which should use less memory overall.
Relates to #613
=> (GH-613) Compute hash using stream 

chocolatey/Website/Views/Events/Files/01-04-TheBusinessValueOfModernizingYourWindowsInfrastructure.md, chocolatey/Website/Views/Pages/Home.cshtml, chocolatey/Website/Views/Pages/_CollapsingRightSidebarContent.cshtml
Updates the time formats shown for the webinar "The Business Value of
Modernizing Your Windows Infrastructure and Bringing Linux & Windows
Teams Closer" on the events page. This also adds the time to the
announcement section on the home page, as that was missing before.
=> (GH-935) Update Puppet Webinar Time on Home/Events Page

chocolatey/Website/Views/Packages/_ListVersion.cshtml
Removes the class that is removing the top borders on the last column
of the Version History Table on the Packages Page.
Fixes #943
=> (GH-943) Add Top Border to Version History Table

chocolatey/Website/Services/UserService.cs
Adjusts the regex used to detect special characters by not including
any letter character, number, or white space instead of listing out
all the special characters.
Fixes #944
=> (GH-944) Adjust Password Regex Special Characters

chocolatey/Website/Views/Packages/_ListPackage.cshtml, chocolatey/Website/Views/Users/Profiles.cshtml
While in the grid view mode on the packages page, package titles will
now break if the title is too long to fit in the box instead of busting
out of the box. This fixes alignment issues with both the title and the
image placement. A Bootstrap class has been added to support this
feature. See:
https://getbootstrap.com/docs/4.4/utilities/text/#word-break
Fixes #947
=> (GH-947) Break Long Titles in Grid View

chocolatey/Website/Views/Pages/Home.cshtml
Correct typo on home page from "Septemeber" to "September".
=> (GH-952) Fix Typo on Home Page

chocolatey/Website/Views/Pages/_CollapsingRightSidebarContent.cshtml
The prev/next buttons on any carousel item currently do not transition
between slides. This was due to a recent addition of the announcement
flyout, where a carousel was added with the same ID that may be found
on other pages. When the same ID is on the page twice, it breaks the
carousel. The ID has been changed to be unique and not match any other
carousel used throughout the website. Now, the prev/next buttons work
as intended.
=> (GH-960) Make Carousel Prev/Next Buttons Function

chocolatey/Website/App_Start/Routes.cs, chocolatey/Website/Controllers/DocumentationController.cs, chocolatey/Website/Views/Documentation/DocumentationLayout.cshtml
In this PR:
* Updates the left side documentation navigation to include a link to the QDE Internet Setup v1 page.
* Address issue to prevent a `-` character to be inserted between a letter and a number when a URL is converted in the documentation area.
Fixes #956
=> (GH-956) Prevent `-` Between Letters and Numbers in URL/ Update Doc Links

chocolatey/Website/Views/Documentation/DocumentationLayout.cshtml
Adds the QDE v1 links to the left side navigation in the documentation
area, under the existing QDE dropdown.
=> (GH-965) Add QDE v1 Links to Docs Nav

chocolatey/Website/Views/Packages/DisplayPackage.cshtml
Allows the Software Author Field to wrap instead of breaking out of
it's bounding box. This applies mostly when the Software Author field
contains a url, or a long word without any breaks.
=> (GH-915) Allow Software Author Field to Wrap

chocolatey/Website/Views/Documentation/DocumentationLayout.cshtml
This moves the QDE Internet Setup doc out of the v1 sidebar dropdown,
and places it directly inside the QDE dropdown. The URL is also
adjusted because of the change of the filename from
`QuickDeploymentInternetSetup-v1.md` to
`QuickDeploymentInternetSetup.md`.
=> (GH-965) Update QDE Doc Navigation Links

chocolatey/Website/App_Start/Routes.cs, chocolatey/Website/Controllers/PagesController.cs
(GH-973) Prevent Form URL from Returning /policies
Whenever a form was submitted, the URL being sent in and returned
always contained `/policies/` in the URL. With this update, this no
longer happens, and the forms are sent in from the URL in which they
come from, and also returned as such.
This bug was introduced in commit https://github.com/chocolatey/chocolatey.org/commit/9abd30456915145653706c7daf34aa2c9e1ba2a5 and happened whenever a form was references like:
`@using (Html.BeginForm("ContactSales", "Pages", FormMethod.Post, new { id = "i-recaptcha" }))`
Fixes #973
=> (GH-973) Prevent Form URL from Returning /policies

chocolatey/Website/Views/Pages/Home.cshtml
Note: To be merged once the Puppet Webinar is over
Removes the Puppet webinar information from the homepage, as the event
date has passed and the replay is not available yet. This
replaces that information with the on-demand information for the
Deployments Webinar.
=> (layout) Remove Puppet Webinar from Homepage

chocolatey/Website/Services/MessageService.cs
Fix a typo in the registration email.
I would suggest running `codespell` over the pages so that we can attract more contributors :-). I was afraid that I would destroy some code accidentally, so I didn't do that. But I'll be glad to help if anyone likes it.
=> Fix a typo

chocolatey/Website/Views/Events/Files/01-04-TheBusinessValueOfModernizingYourWindowsInfrastructure.md
Updates the link to the Puppet Webinar so users can watch on-demand.
=> (maint) Update Puppet Webinar On-Demand Link

chocolatey/Website/.well-known/security.txt, chocolatey/Website/Web.config, chocolatey/Website/Website.csproj
Includes a security.txt file for users to better understand the best
way to report vulnerabilities.
The url chocolatey.org/security.txt will redirect to
chocolatey.org/.well-known/security.txt
Fixes #970
=> (GH-970) Include a security.txt file

chocolatey/Website/Views/Pages/_CollapsingRightSidebarContent.cshtml
Updates the link to the on-demand replay of the Puppet webinar that
is found in the right side announcement bar.
=> (maint) Update Puppet Webinar Link in Sidebar

chocolatey/Website/Content/scss/_alerts.scss, chocolatey/Website/Content/scss/_base.scss, chocolatey/Website/Content/scss/_chocolatey-variables.scss, chocolatey/Website/Content/scss/chocolatey.scss, chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Shared/_AlertTop.cshtml, chocolatey/Website/Views/Shared/_CookiePolicy.cshtml, chocolatey/Website/Website.csproj
The cookie set by the cookie banner notice has been set to have the
domain of chocolatey.org. This will allow the cookie to be read and
used on the main chocolatey.org and any subdomain.
If the cookie is set on a local environment, it will not be set with
this property. This has been done so that the cookie still works and
can be tested while running locally. The cross domain
functionality will only work on the actual live site.
This also slightly enhances the styling and uses a consistent format
that will be used across subdomains visually.
Fixes #1000
=> (GH-1000) Make Cookie Work Across All Domains

chocolatey/Website/Views/Shared/_BaseLayout.cshtml
Updates the Google Analytics snippet to the recommended usage provided
by Google. The previous implementation was using a legacy helper to
generate an outdated snippet.
https://docs.microsoft.com/en-us/previous-versions/gg547914(v=vs.99)
Fixes #1006
=> (GH-1006) Update Google Analytics Snippet

chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml
Corrects a typo in a speakers name on the new 12 Days of Chocolatey
page.
=> (maint) Fix Typo in Speaker Name

chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml
Updates "live stream" to "livestream" and makes the text in the header
a little more clear and readable on the 12 Days of Chocolatey event page.
=> (maint) Adjust Wording on 12 Days Page

chocolatey/Website/Content/calendars/12DaysOfChocolatey-01December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-02December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-04December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-07December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-08December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-09December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-11December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-14December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-15December2020.ics, chocolatey/Website/Content/calendars/12DaysOfChocolatey-16December2020.ics, chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml, chocolatey/Website/Website.csproj
Adds an "Add to Calendar" button to the 12 Days of Chocolatey event
page under each event. Calendars are included for Google, Yahoo, iCal,
and Outlook.
=> (events) Add an "Add to Calendar" Button

chocolatey/Website/Scripts/custom.js, chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml, chocolatey/Website/Views/Events/ChocolateyDeploymentSchedules.cshtml, chocolatey/Website/Views/Events/ChocolateyDeployments.cshtml, chocolatey/Website/Views/Events/EnableYourRemoteWorkforceByImplementingModernInfrastructureWithChocolatey.cshtml
Adds support for multi event to the countdown timer. If there is more
than 1 event date listed, the timer will automatically lapse over
to the next available time until each time has past. When there are no
more times, then the timer will be removed like how it currently is.
=> (events) Add Multi Event Support for Countdown

chocolatey/Website/Views/Events/12DaysOfChocolatey.cshtml, chocolatey/Website/Views/Shared/_LivestreamShare.cshtml
In this PR:
* Removes Twitter as a streaming platform for The 12 Days of Chocolatey
* Adds replay links to expired events for The 12 Days of Chocolatey
=> (events) Update streaming platforms and add replays

chocolatey/Website/Scripts/package-list/package-list.js, chocolatey/Website/Views/Packages/ListPackages.cshtml, chocolatey/Website/Views/Shared/_SearchBox.cshtml
This removes the site results tab from the packages page. The search
now only shows package results. The Google Search js has also been
removed.
Fixes #1029
=> (GH-1029) Remove Site Results Tab from Search

build.cake, chocolatey/Website/Entities/Course.cs, chocolatey/Website/Entities/CourseModule.cs, chocolatey/Website/Entities/Package.cs, chocolatey/Website/Entities/PackageFramework.cs, chocolatey/Website/RequestModels/RegisterRequest.cs, chocolatey/Website/Services/PackageService.cs, chocolatey/Website/ViewModels/PasswordResetViewModel.cs, chocolatey/Website/Web.config, chocolatey/Website/Website.csproj, chocolatey/Website/packages.config
In order to accomplish this, it was necessary to upgrade EntityFramework
package to 5.0.0.  This was due to the fact that some attributes that
are being used on the entity classes have moved to a new namespace.
The necessary attribute changes have been made.
In addition, it was necessary to add the NotMapped attribute to a number
of properties, otherwise EF was changing that a migration was required
to be added.  My assumption here is that in EF 5.0.0 there has been a
change in how mapped properties were discovered. In EF 4.3.1 the
NotMapped attribute was not required, but now it is.
Where necessary, NuGet packages were uninstalled and re-installed in
order to re-target to .NET Framework 4.5.2.
Fixes #1039 
I am going to put this up on the Test Site, and I will comment on this PR when …
=> Upgrade to .NET Framework 4.5.2
